name: CI - Validación HTML, CSS y JS

on:
  push:
    branches: [main]

jobs:
  validar-codigo:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      # --- HTMLHINT ---
      - name: Instalar htmlhint
        run: npm install -g htmlhint

      - name: Ejecutar htmlhint
        run: htmlhint .

      # --- STYLELINT ---
      - name: Instalar stylelint
        run: npm install -g stylelint stylelint-config-standard

      - name: Crear archivo de configuración stylelint
        run: |
          echo '{
            "extends": "stylelint-config-standard"
          }' > .stylelintrc.json

      - name: Ejecutar stylelint
        run: stylelint "**/*.css"

      # --- ESLINT (compatible con ESLint v9+) ---
      - name: Instalar eslint
        run: npm install -g eslint

      - name: Crear archivo de configuración eslint (nuevo formato)
        run: |
          echo 'export default [
            {
              files: ["**/*.js"],
              languageOptions: {
                ecmaVersion: "latest",
                sourceType: "module"
              },
              rules: {
                semi: ["error", "always"],
                "no-unused-vars": "warn"
              }
            }
          ];' > eslint.config.js

      - name: Ejecutar eslint
        run: eslint "**/*.js"
