name: CI - Validación HTML, CSS y JS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validar-codigo:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # --- HTMLHINT ---
      - name: Instalar y ejecutar htmlhint
        run: |
          npx htmlhint "**/*.html"

      # --- STYLELINT ---
      - name: Instalar y ejecutar stylelint
        run: |
          echo '{"extends": "stylelint-config-standard"}' > .stylelintrc.json
          npx stylelint "**/*.css"

      # --- ESLINT ---
      - name: Instalar y ejecutar eslint
        run: |
          echo 'export default [
            {
              files: ["**/*.js"],
              languageOptions: {
                ecmaVersion: "latest",
                sourceType: "module"
              },
              rules: {
                "semi": ["error", "always"],
                "no-unused-vars": "warn",
                "no-console": "warn"
              }
            }
          ];' > eslint.config.js
          npx eslint "**/*.js"