name: CI y CD - Validación + Despliegue

on:
  push:
    branches: [main]

jobs:
  validar-y-desplegar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      #########################
      ## VALIDACIÓN DEL CÓDIGO
      #########################

      # HTMLHINT
      - name: Instalar htmlhint
        run: npm install -g htmlhint

      - name: Ejecutar htmlhint
        run: htmlhint html/

      # STYLELINT
      - name: Instalar stylelint
        run: npm install -g stylelint stylelint-config-standard

      - name: Crear configuración stylelint
        run: |
          echo '{
            "extends": "stylelint-config-standard"
          }' > .stylelintrc.json

      - name: Ejecutar stylelint
        run: stylelint "css/**/*.css"

      # ESLINT
      - name: Instalar eslint
        run: npm install -g eslint

      - name: Crear configuración eslint
        run: |
          echo 'export default [
            {
              files: ["js/**/*.js"],
              languageOptions: {
                ecmaVersion: "latest",
                sourceType: "module"
              },
              rules: {
                semi: ["error", "always"],
                "no-unused-vars": "warn"
              }
            }
          ];' > eslint.config.js

      - name: Ejecutar eslint
        run: eslint "js/**/*.js"

      #########################
      ## DESPLIEGUE CONTINUO
      #########################

      - name: Preparar carpeta de publicación
        run: |
          mkdir public
          cp -r html/* public/
          cp -r css public/
          cp -r js public/

      - name: Subir a GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
