name: CI - Validación HTML, CSS y JS

on:
  push:
    branches: [main]

jobs:
  validar-codigo:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      # --- HTMLHINT ---
      - name: Instalar htmlhint
        run: npm install -g htmlhint

      - name: Ejecutar htmlhint
        run: htmlhint .

      # --- STYLELINT ---
      - name: Instalar stylelint
        run: npm install -g stylelint stylelint-config-standard

      - name: Crear archivo de configuración stylelint
        run: |
          echo '{
            "extends": "stylelint-config-standard"
          }' > .stylelintrc.json

      - name: Ejecutar stylelint
        run: stylelint "**/*.css"

      # --- ESLINT ---
      - name: Instalar eslint
        run: npm install -g eslint

      - name: Crear archivo de configuración eslint
        run: |
          echo '{
            "env": {
              "browser": true,
              "es2021": true
            },
            "extends": "eslint:recommended"
          }' > .eslintrc.json

      - name: Ejecutar eslint
        run: eslint "**/*.js"
