name: Verificar archivos HTML

on:
  push:
    paths:
      - '**.html'

jobs:
  mensaje-html:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Imprimir mensaje en consola
        run: echo "✅ Archivos HTML detectados. Todo está correcto."
