name: CI para HTML simple

on:
  push:
    branches:
      - main

jobs:
  check-html:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar htmlhint
        run: npm install -g htmlhint

      - name: Verificar archivos HTML
        run: htmlhint . --ext .html

      - name: Fin del proceso
        run: echo "✅ Verificación HTML terminada"
